# Generated by Django 3.0.2 on 2020-03-03 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 3, 11, 49, 1, 918277)),
        ),
    ]
