# Generated by Django 3.0.2 on 2020-03-04 04:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 4, 4, 37, 43, 525773, tzinfo=utc)),
        ),
    ]
