# Generated by Django 3.0.2 on 2020-03-04 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20200304_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 4, 4, 43, 6, 279667)),
        ),
    ]
