# Generated by Django 3.0.2 on 2020-03-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200302_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='username',
            new_name='user',
        ),
    ]
