# Generated by Django 3.0.2 on 2020-02-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_gym_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='gym_image'),
        ),
    ]
