# Generated by Django 3.0.2 on 2020-02-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200226_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
