# Generated by Django 3.0.2 on 2020-02-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200226_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='image',
            field=models.ImageField(null=True, upload_to='gym_image'),
        ),
    ]
