# Generated by Django 3.0.2 on 2020-02-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200226_0722'),
        ('accounts', '0007_auto_20200226_0635'),
    ]

    operations = [
    ]
