# Generated by Django 3.0.2 on 2020-02-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20200226_1057'),
        ('accounts', '0008_gym_category'),
    ]

    operations = [
    ]
